---
title: "GenerateBED"
author: "Vini Karumuru"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(biomaRt)
library(dplyr)
library(gtools)
```

```{r}
# load in list of EwS-associated genes
gene_list = read.csv("ews_associated_gene_list.csv") %>%
            select(Gene) %>%
            unlist()
gene_list
```

```{r}
# select BioMart database and dataset to use
mart = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
```

```{r}
# retrieve desired values from BioMart database
bed_data = getBM(attributes = c("external_gene_name",
                                "chromosome_name",
                                "start_position",
                                "end_position"),
                 filters = "external_gene_name",
                 values = gene_list,
                 mart = mart)
bed_data
```

```{r}
# looking at unique chromosome names
unique(bed_data$chromosome_name)
```

```{r}
export_bed = bed_data %>%
             # removing unknown chromosomes/contigs
             filter(!grepl("HSCH|HG", chromosome_name)) %>%
              
             # adding "chr" to chromosome names to match .vcf files
             mutate(chromosome_name = paste0("chr",chromosome_name)) %>%
            
             # sorting by chromosome name, then position
             slice(mixedorder(chromosome_name)) %>%
             arrange(match(chromosome_name, unique(chromosome_name)), start_position)

export_bed
```


```{r}
# exporting as a .bed file
write.table(export_bed, 
            file = "EwSAscGenes.bed", 
            quote = FALSE, 
            sep = "\t", 
            col.names = FALSE, 
            row.names = FALSE)
```