---
title: "VariantAnalysis"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(gt)
library(patchwork)
library(UpSetR)
```

# Generate the variants data frame

```{r}
variants = read_tsv(file = "~/bioinfo/EwsProject/Variant-Analysis/variantspercellline.tsv")
```

# Exploratory Data Anaylsis

```{r}
genes_per_cell_line = variants %>% 
  dplyr::select(Cell_Line, Gene) %>% 
  distinct() %>% 
  count(Cell_Line)

genes_per_cell_line = genes_per_cell_line %>% 
  dplyr::rename(`Genes` = n, `Cell Line` = Cell_Line)

genes_per_cell_line %>% 
  gt() %>% 
  tab_header(title = "# of Genes that have Variants in Each Cell Line")
```

```{r}
unique_genes_per_cell_line = variants %>%
  distinct(Cell_Line, Gene, .keep_all = TRUE) %>%
  group_by(Gene) %>%
  mutate(cell_count = n_distinct(Cell_Line)) %>%
  filter(cell_count == 1) %>% 
  ungroup()


unique_gene_count = unique_genes_per_cell_line %>% 
  count(Cell_Line) %>% 
  dplyr::rename(`Cell Line` = Cell_Line, `Genes` = n)

unique_gene_count %>% 
  gt() %>% 
  tab_header(title = "# of Unique Genes with Variants per Cell Line")
```

```{r}
variants %>% 
  na.omit(variants) %>% 
  mutate(count = 1) %>% 
  ggplot(aes(x = Cell_Line, y = count, fill = Variant_Type)) +
  geom_bar(stat = "identity") +
  labs(y = "# of Variants", x = "Cell Line", fill = "Variant Type", title = "Number of Variants per Cell Line") +
  scale_fill_manual(values = c("Breakpoint" = "red", 
                               "Deletion" = "blue", 
                               "Duplication" = "steelblue", 
                               "Insertion" = "lightblue"))
```

# Graph for the types of variants in each cell type

```{r}
insertions = variants %>% 
  na.omit(variants) %>%
  filter(Variant_Type == "Insertion") %>% 
  mutate(count = 1) %>% 
  ggplot(aes(x = Cell_Line, y = count)) +
  geom_bar(stat = "identity", color = "blue") +
  labs(y = "", x = "", title = "Insertions") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


deletions = variants %>% 
  na.omit(variants) %>%
  filter(Variant_Type == "Deletion") %>% 
  mutate(count = 1) %>% 
  ggplot(aes(x = Cell_Line, y = count)) +
  geom_bar(stat = "identity", color = "steelblue") +
  labs(y = "", x = "", title = "Duplications") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


duplications = variants %>% 
  na.omit(variants) %>%
  filter(Variant_Type == "Duplication") %>% 
  mutate(count = 1) %>% 
  ggplot(aes(x = Cell_Line, y = count)) +
  geom_bar(stat = "identity", color = "steelblue") +
  labs(y = "", x = "", title = "Duplications") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


breakpoints = variants %>% 
  na.omit(variants) %>%
  filter(Variant_Type == "Breakpoint") %>% 
  mutate(count = 1) %>% 
  ggplot(aes(x = Cell_Line, y = count)) +
  geom_bar(stat = "identity", color = "darkblue") +
  labs(y = "", x = "", title = "Breakpoints") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


((insertions + deletions) / (duplications + breakpoints)) + 
  plot_annotation(
    title = "Number of Variants within Genes per Cell Line",
    caption = "X Axis: Cell Line | Y Axis: Number of Variants"
  )

```
```{r, fig.height=10, fig.width=15}
genes_per_cellline_list = list(
  A673 = c(variants %>% filter(Cell_Line == "A673") %>% .$Gene),
  A4573 = c(variants %>% filter(Cell_Line == "A4573") %>% .$Gene),
  CHLA9 = c(variants %>% filter(Cell_Line == "CHLA9") %>% .$Gene),
  CHLA10 = c(variants %>% filter(Cell_Line == "CHLA10") %>% .$Gene),
  PDX305 = c(variants %>% filter(Cell_Line == "PDX305") %>% .$Gene),
  RDES = c(variants %>% filter(Cell_Line == "RDES") %>% .$Gene),
  SKNMC = c(variants %>% filter(Cell_Line == "SKNMC") %>% .$Gene),
  TC32 = c(variants %>% filter(Cell_Line == "TC32") %>% .$Gene),
  TC71 = c(variants %>% filter(Cell_Line == "TC71") %>% .$Gene)
)

data_list = fromList(genes_per_cellline_list)
upset(data_list, 
      sets = c("A673", "A4573", "CHLA9","CHLA10","PDX305","RDES","SKNMC","TC32","TC71"),
      order.by = "freq",
      number.angles = 0, point.size = 3, line.size = 1, 
      mainbar.y.label = "# of Shared Genes", sets.x.label = "# of Genes per Cell Line",
      sets.bar.color = "blue",
      main.bar.color = "blue",
      matrix.color = "blue",
      text.scale = c(3, 1.5, 1.75, 1, 2, 1.5))
```
```{r, fig.height=10, fig.width=15}
variants$gene_and_variant = paste(variants$Gene, variants$Variant_Type, sep = ":")

gene_and_variant_per_cellline_list = list(
  A673 = c(variants %>% filter(Cell_Line == "A673") %>% .$gene_and_variant),
  A4573 = c(variants %>% filter(Cell_Line == "A4573") %>% .$gene_and_variant),
  CHLA9 = c(variants %>% filter(Cell_Line == "CHLA9") %>% .$gene_and_variant),
  CHLA10 = c(variants %>% filter(Cell_Line == "CHLA10") %>% .$gene_and_variant),
  PDX305 = c(variants %>% filter(Cell_Line == "PDX305") %>% .$gene_and_variant),
  RDES = c(variants %>% filter(Cell_Line == "RDES") %>% .$gene_and_variant),
  SKNMC = c(variants %>% filter(Cell_Line == "SKNMC") %>% .$gene_and_variant),
  TC32 = c(variants %>% filter(Cell_Line == "TC32") %>% .$gene_and_variant),
  TC71 = c(variants %>% filter(Cell_Line == "TC71") %>% .$gene_and_variant)
)

data_list2 = fromList(gene_and_variant_per_cellline_list)
upset(data_list2, 
      sets = c("A673", "A4573", "CHLA9","CHLA10","PDX305","RDES","SKNMC","TC32","TC71"),
      order.by = "freq",
      mainbar.y.label = "# of Shared Variants in Genes", sets.x.label = "# of Variants in Genes per Cell Line",
      number.angles = 0, point.size = 3, line.size = 1, 
      sets.bar.color = "blue",
      main.bar.color = "blue",
      matrix.color = "blue",
      text.scale = c(3, 1.5, 1.75, 1, 2, 1.5))
```

# Exploring other fusions: attempting to back up their legitimacy

```{r}
variants %>% 
  filter(Variant_Type == "Breakpoint" & (Gene == "EWSR1")) %>% 
  count(Cell_Line)

variants %>% 
  filter(Variant_Type == "Breakpoint" & (Gene == "FLI1")) %>% 
  count(Cell_Line)
```
```{r}
breakpoints = variants %>% 
  filter(Variant_Type == "Breakpoint")
```

## HIVEP3 SUCLA2 Possible Fusion Only
```{r}
breakpoints %>% 
  filter(Gene != "FLI1" & Gene != "EWSR1") %>% 
  filter(Cell_Line == "A673" | Cell_Line == "CHLA10" | Cell_Line == "TC32") %>% 
  filter(Gene == "HIVEP3" | Gene == "SUCLA2")
```