---
title: "EDA"
author: "Josh Kramer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Seurat)
library(Signac) 
library(ggplot2)
library(patchwork)
library(biomaRt)
library(readxl)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(org.Hs.eg.db)
library(VariantAnnotation)
```

# Getting known genes bed file
```{r}
EwSAssiocatedGenes = read_excel("/Users/joshkramer/Documents/EDA/EwS-AssociatedGenes.xlsx")
mart = useMart("ensembl", dataset = "hsapiens_gene_ensembl")

bed_data = getBM(
  attributes = c("chromosome_name", "start_position", "end_position", "external_gene_name"),
  filters = "external_gene_name",
  values = EwSAssiocatedGenes$`Gene Name`,
  mart = mart
)


datasets = listDatasets(mart)


bed_data = bed_data %>% relocate(external_gene_name, .after = end_position)

canonical_chrom = c(as.character(1:22), "X", "Y")

bed_data = bed_data %>% filter(chromosome_name %in% canonical_chrom)

```

# Creating and sorting the bed file
```{r}

chrom_order = c(as.character(1:22), "X", "Y")

bed_data$chromosome_name = factor(bed_data$chromosome_name, levels = chrom_order, ordered = TRUE)

bed_data_sorted = bed_data[order(bed_data$chromosome_name, bed_data$start_position), ]


bed_data_sorted = bed_data_sorted %>% 
  mutate(chromosome_name = paste("chr",chromosome_name, sep=""))

write.table(bed_data_sorted, file = "EwSAscGenes.bed", col.names = FALSE, row.names = FALSE, quote = FALSE, sep = "\t")

```

# Getting all known genes bed file
```{r}
mart = useMart("ensembl", dataset = "hsapiens_gene_ensembl")

all_genes = getBM(
  attributes = c("chromosome_name", "start_position", "end_position", "external_gene_name"),
  mart = mart
)


all_genes = all_genes %>% relocate(external_gene_name, .after = end_position)

canonical_chrom = c(as.character(1:22), "X", "Y")

all_genes = all_genes %>% filter(chromosome_name %in% canonical_chrom)


all_genes = all_genes %>% filter(external_gene_name != "")
```

# Creating and sorting the bed file
```{r}

chrom_order = c(as.character(1:22), "X", "Y")

all_genes$chromosome_name = factor(all_genes$chromosome_name, levels = chrom_order, ordered = TRUE)

all_genes_sorted = all_genes[order(all_genes$chromosome_name, all_genes$start_position), ]


all_genes_sorted = all_genes_sorted %>% 
  mutate(chromosome_name = paste("chr",chromosome_name, sep=""))

write.table(all_genes_sorted, file = "HumanGenes.bed", col.names = FALSE, row.names = FALSE, quote = FALSE, sep = "\t")

```